repos:
  # Comentado temporariamente devido a problemas de compilação do Go
  # - repo: https://github.com/gitleaks/gitleaks
  #   rev: v8.19.3
  #   hooks:
  #     - id: gitleaks
  #       stages: [pre-commit]
  #       args: ["--verbose"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-symlinks

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: npm-test
        name: Run npm tests
        entry: npm test
        language: system
        types: [javascript, ts]
        pass_filenames: false
        stages: [pre-commit]
